apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "felice.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "felice.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "felice.fullname" . }}-hs
  replicas: 1 
  updateStrategy:
    type: RollingUpdate 
  podManagementPolicy: OrderedReady 
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "felice.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "felice.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostAliases:
        - hostnames:
          - felice-mon
          - felice-api
          - felice-back
          - felice-front
          - felice-lag
          ip: "127.0.0.1"
      containers:
      #### felice-mon ####
      - name: {{ .Chart.Name }}-mon
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.images.registry }}/prometheus-spark:{{ .Values.images.monitorVersion }}"
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        ports:
        - containerPort: 9090
          name: felice-mon
        readinessProbe:
          httpGet:
            port: felice-mon
            path: /-/healthy
          timeoutSeconds: 2
        startupProbe:
          tcpSocket:
            port: felice-mon
          initialDelaySeconds: 10
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        # command:
        args:
          - --web.enable-lifecycle
          - --web.enable-admin-api
          - --storage.tsdb.retention.time=120d
          {{- $storage := mustRegexFind "[0-9]+" .Values.configs.volumes.tsdb.storage | atoi }}
          {{- $storage = div (mul $storage 3) 4 }}
          - --storage.tsdb.retention.size={{ $storage }}GiB
        # env:
        #   - name: PROMETHEUS_STORAGE_TSDB_RETENTION_TIME
        #     value: 60d
        volumeMounts:
        - name: {{ include "felice.fullname" . }}-monitoring-tsdb
          mountPath: /prometheus
        - name: {{ include "felice.fullname" . }}-rulesdir
          mountPath: /opt/felice/rules
          readOnly: true
        - name: monitoring-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: monitoring-targets
          mountPath: /etc/prometheus/targets
      #### FELICE-BACK ####
      - name: {{ .Chart.Name }}-api
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.images.registry }}/felice-api-server:{{ .Values.images.serverVersion }}"
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        ports:
        - containerPort: 8989
          name: felice-api
        readinessProbe:
          httpGet:
            port: 7100
            path: /monitor/health
          timeoutSeconds: 2
        startupProbe:
          tcpSocket:
            port: felice-api
          initialDelaySeconds: 30
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        # env:
        volumeMounts:
        - name: {{ include "felice.fullname" . }}-rulesdir
          mountPath: /felice-api/prom-rules
        - name: {{ include "felice.fullname" . }}-datadir
          mountPath: /felice-api/data
      #### FELICE-FRONT ####
      - name: {{ .Chart.Name }}-front
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.images.registry }}/felice-client:{{ .Values.images.clientVersion }}"
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        ports:
        - containerPort: 8080
          name: felice-front
        readinessProbe:
          httpGet:
            port: felice-front
            path: /monitor/health
          timeoutSeconds: 2
        startupProbe:
          tcpSocket:
            port: felice-front
          initialDelaySeconds: 10
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        # env:
      #### FELICE-LAG ####
      - name: {{ .Chart.Name }}-lag
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.images.registry }}/burrow-spark:latest"
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        ports:
        - containerPort: 8000
          name: felice-lag
        readinessProbe:
          httpGet:
            port: felice-lag
            path: /burrow/admin/ready
          timeoutSeconds: 2
        startupProbe:
          tcpSocket:
            port: felice-lag
          initialDelaySeconds: 10
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: BURROW_YAML
          valueFrom:
            configMapKeyRef:
              name: {{ include "felice.fullname" . }}-config
              key: burrow.yaml       
      volumes:
        - name: monitoring-config
          emptyDir: {}
        - name: monitoring-targets
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # {{- with .Values.affinity }}
      # affinity:
      #   {{- toYaml . | nindent 8 }}
      # {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - {{ include "felice.fullname" . }}
              topologyKey: "kubernetes.io/hostname"
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # volumes:
      #   - name: burrow-toml-volume
      #     configMap:
      #       name: {{ include "felice.fullname" . }}-burrow
